@startuml
title Obtener Rol de Usuario - Dominio

actor Usuario as U
participant ServicioLogin as SL
entity User as US
entity UserRole as UR
entity Rol as R

U -> SL: getRoleUser(username)

SL -> US: buscar usuario por username

alt usuario no existe
    SL --> U: retornar null (no encontrado)
else usuario existe
    US -> UR: obtener relación Usuario - Rol
    UR -> R: obtener rol asociado
 
    SL --> U: retornar Rol de usuario
end

@enduml
